version: 6
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         name: Download Dependencies
#         command: ./gradlew androidDependencies
      - run:
          name: Download Dependencies
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - run:
          name: Upload to Google Play
          command: ./gradlew publishRelease